### ISSUE TITLE
Request for limited redistribution permission

### ISSUE THREAD

**Issue by firefu-mc** [gentlegiantJGC/PyMCTranslate#14]
Hi,
I realised I can't send PMs on github - so I've opened a new ticket for this.

I hadn't though to check for a license for PyMCTranslate, as my only direct dependency is Amulet-Core - I wasn't particularly aware that it depended on PyMCTranslate until I had the problem mentioned in GH-13.
Your message reminded me that I've had a ticket open under Amulet-Core for a few months asking about a license - I just checked it and saw that it's assigned to you (gentlegiantJGC) - so I'm hoping it's appropriate to ask about licensing for both PyMCTranslate and Amulet-Team projects here.

Would you consider granting me express permission to redistribute Amulet-Core, PyMCTranslate and Amulet-NBT (as another indirect dependency) for the sole purpose of me providing compiled executable versions of my "Minecraft Muncher" application?
[https://github.com/firefu-mc/mcmuncher](https://github.com/firefu-mc/mcmuncher)

The executables would only be distributed through github, and my project will be entirely opensource, free and non-commercial.

I'd be happy to include any copyright, attribution, and short message about these 3 projects you deem necessary, as well as links to their project pages and to the Amulet Editor website.

The purpose of my program is to provide convenience methods for repetitive admin tasks, that are less suited to a map-based GUI such as Amulet-Map-Editor - such as trimming worlds down to a defined border size - something that a server admin might want to do regularly.

**Comment by JacobKotrla** [comment]
Just discovered this program, and the license on this library seems to be explicitly *not* open source unfortunately. And I'm not sure exactly where the boundaries of the license are (e.g. selling the software is not allowed, but could I pay someone to improve the software and send it to me?). If the project is going to use a license, I wish they would just use a well understood and [OSI-approved license](https://opensource.org/licenses) to reduce confusion and maximize freedom. I think that would solve this issue.
